# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: csv_patch 1.2.0 ruby lib

Gem::Specification.new do |s|
  s.name = "csv_patch".freeze
  s.version = "1.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Lyudmil".freeze]
  s.date = "2021-04-06"
  s.description = "Applies a list of changes in a given format to a CSV file".freeze
  s.email = "lyudmilangelov@gmail.com".freeze
  s.executables = ["csv_patch".freeze]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "Rakefile",
    "VERSION",
    "bin/csv_patch",
    "csv_patch.gemspec",
    "lib/csv_patch.rb",
    "lib/csv_patch/batches.rb",
    "lib/csv_patch/compression.rb",
    "lib/csv_patch/operation.rb",
    "lib/csv_patch/patch.rb",
    "lib/csv_patch/revision.rb",
    "lib/csv_patch/stream_batch.rb"
  ]
  s.rubygems_version = "3.0.9".freeze
  s.summary = "Apply diffs to a CSV file".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>.freeze, [">= 0"])
      s.add_development_dependency(%q<mocha>.freeze, [">= 0"])
      s.add_development_dependency(%q<minitest>.freeze, [">= 0"])
    else
      s.add_dependency(%q<jeweler>.freeze, [">= 0"])
      s.add_dependency(%q<mocha>.freeze, [">= 0"])
      s.add_dependency(%q<minitest>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<jeweler>.freeze, [">= 0"])
    s.add_dependency(%q<mocha>.freeze, [">= 0"])
    s.add_dependency(%q<minitest>.freeze, [">= 0"])
  end
end

